## catalog of libraries and plugins used to build the jolt-jni-droid project

[versions]

agp = "8.9.3"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
joltjni = "3.4.0"
material = "1.13.0"
navigation = "2.9.6"

[libraries]

appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
jolt-jni = { group = "com.github.stephengold", name = "jolt-jni-Android", version.ref = "joltjni" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }

[bundles]

[plugins]

android-application = { id = "com.android.application", version.ref = "agp" }
