---
# GitHub Actions workflow for commits pushed to the jolt-jni-droid repo - master branch

name: CI at GitHub
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  Java17-x-Android:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v6
      - uses: gradle/actions/setup-gradle@v5
      - name: gradlew build
        run: |
          ./gradlew build \
            --console=plain --stacktrace
